from .user_model import User
from .personagens_model import Personagem
from .nomes_model import Nome
from .arma_model import Arma
from .armadura_model import Armadura
from .equipamento_model import Equipamento
from .habilidade_model import Habilidade
from .acoes_model import AcoesEspeciais
from .reacoes_model import Reacoes
from .lendarias_model import Lendarias
from .magias_model import Magias
from .classe_model import Classe