"""empty message

Revision ID: 481093ba536c
Revises: be649d75a46a
Create Date: 2024-09-24 02:31:43.714435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481093ba536c'
down_revision = 'be649d75a46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('armadura', schema=None) as batch_op:
        batch_op.alter_column('forca',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('armadura', schema=None) as batch_op:
        batch_op.alter_column('forca',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
