"""empty message

Revision ID: 4aac55a469e9
Revises: 58c3e51ec55e
Create Date: 2024-10-07 02:33:17.276345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aac55a469e9'
down_revision = '58c3e51ec55e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encontros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encontro', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campanha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('campanha', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('cenario', sa.JSON(), nullable=False),
    sa.Column('tipo', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cenario_campanha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cenario', sa.Integer(), nullable=False),
    sa.Column('id_campanha', sa.Integer(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_campanha'], ['campanha.id'], ),
    sa.ForeignKeyConstraint(['id_cenario'], ['cenario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encontros_campanha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_encontro', sa.Integer(), nullable=False),
    sa.Column('id_campanha', sa.Integer(), nullable=False),
    sa.Column('notas', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['id_campanha'], ['campanha.id'], ),
    sa.ForeignKeyConstraint(['id_encontro'], ['encontros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('npcs_campanha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campanha_id', sa.Integer(), nullable=True),
    sa.Column('id_personagem', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['campanha_id'], ['campanha.id'], ),
    sa.ForeignKeyConstraint(['id_personagem'], ['personagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizacoes_campanha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_organizacao', sa.Integer(), nullable=False),
    sa.Column('id_campanha', sa.Integer(), nullable=False),
    sa.Column('notas', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_campanha'], ['campanha.id'], ),
    sa.ForeignKeyConstraint(['id_organizacao'], ['organizacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personagens', schema=None) as batch_op:
        batch_op.alter_column('id_user',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personagens', schema=None) as batch_op:
        batch_op.alter_column('id_user',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('organizacoes_campanha')
    op.drop_table('npcs_campanha')
    op.drop_table('encontros_campanha')
    op.drop_table('cenario_campanha')
    op.drop_table('cenario')
    op.drop_table('campanha')
    op.drop_table('organizacoes')
    op.drop_table('encontros')
    # ### end Alembic commands ###
