"""empty message

Revision ID: 58c3e51ec55e
Revises: 8f94b3b02502
Create Date: 2024-09-24 16:45:24.420136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c3e51ec55e'
down_revision = '8f94b3b02502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipamento', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('nome_original',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipamento', schema=None) as batch_op:
        batch_op.alter_column('nome_original',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###
