"""empty message

Revision ID: be649d75a46a
Revises: 
Create Date: 2024-09-23 13:49:02.984334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be649d75a46a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acoesespeciais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('efeito_nd', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acao')
    )
    op.create_table('arma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('nome_original', sa.String(length=40), nullable=False),
    sa.Column('categoria', sa.String(length=40), nullable=False),
    sa.Column('tipo_dano', sa.String(length=40), nullable=False),
    sa.Column('dado_dano', sa.String(length=40), nullable=False),
    sa.Column('propriedades', sa.String(length=40), nullable=False),
    sa.Column('maestria', sa.String(length=40), nullable=False),
    sa.Column('peso', sa.String(length=40), nullable=False),
    sa.Column('preco', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('nome_original')
    )
    op.create_table('armadura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('nome_original', sa.String(length=40), nullable=False),
    sa.Column('categoria', sa.String(length=40), nullable=False),
    sa.Column('classe_armadura', sa.String(length=40), nullable=False),
    sa.Column('forca', sa.Integer(), nullable=False),
    sa.Column('furtividade', sa.Boolean(), nullable=False),
    sa.Column('peso', sa.String(length=40), nullable=False),
    sa.Column('preco', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('nome_original')
    )
    op.create_table('classe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('dado_de_vida', sa.String(length=10), nullable=False),
    sa.Column('save1', sa.String(length=15), nullable=False),
    sa.Column('save2', sa.String(length=15), nullable=False),
    sa.Column('pericias', sa.Text(), nullable=False),
    sa.Column('prof_arma', sa.String(length=200), nullable=False),
    sa.Column('prof_armadura', sa.Text(), nullable=False),
    sa.Column('equipamento', sa.Text(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('multiclasse', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('equipamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('nome_original', sa.String(length=40), nullable=False),
    sa.Column('descrição', sa.String(length=512), nullable=False),
    sa.Column('peso', sa.String(length=40), nullable=True),
    sa.Column('preco', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('nome_original')
    )
    op.create_table('habilidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habilidade', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('efeito_nd', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habilidade')
    )
    op.create_table('lendarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acaolendaria', sa.String(length=100), nullable=False),
    sa.Column('custo', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('efeito_nd', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acaolendaria')
    )
    op.create_table('magias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('nome_original', sa.String(length=40), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('escola', sa.String(length=120), nullable=False),
    sa.Column('descrição', sa.Text(), nullable=False),
    sa.Column('descrição_original', sa.Text(), nullable=True),
    sa.Column('tempo', sa.String(length=120), nullable=False),
    sa.Column('alcance', sa.String(length=120), nullable=False),
    sa.Column('componentes', sa.String(length=120), nullable=False),
    sa.Column('duracao', sa.String(length=120), nullable=False),
    sa.Column('efeito_nd', sa.String(length=150), nullable=False),
    sa.Column('livro', sa.String(length=120), nullable=False),
    sa.Column('classes', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('nome_original')
    )
    op.create_table('nome',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('raca', sa.String(length=15), nullable=False),
    sa.Column('sexo', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('reacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reacao', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('efeito_nd', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reacao')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=True),
    sa.Column('sobrenome', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.String(length=550), nullable=False),
    sa.Column('tipo', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('personagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('ficha', sa.JSON(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personagens')
    op.drop_table('user')
    op.drop_table('reacoes')
    op.drop_table('nome')
    op.drop_table('magias')
    op.drop_table('lendarias')
    op.drop_table('habilidade')
    op.drop_table('equipamento')
    op.drop_table('classe')
    op.drop_table('armadura')
    op.drop_table('arma')
    op.drop_table('acoesespeciais')
    # ### end Alembic commands ###
