"""empty message

Revision ID: d8b385c9b93e
Revises: be28cbe5c648
Create Date: 2024-10-09 23:18:48.951197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b385c9b93e'
down_revision = 'be28cbe5c648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('magia', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('magias')
    # ### end Alembic commands ###
