"""empty message

Revision ID: fe1bf3e3fd38
Revises: d8b385c9b93e
Create Date: 2024-10-18 13:30:53.465753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe1bf3e3fd38'
down_revision = 'd8b385c9b93e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_organizacoes_user', 'user', ['id_user'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizacoes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_organizacoes_user', type_='foreignkey')
        batch_op.drop_column('id_user')

    # ### end Alembic commands ###
